export const UPDATE_ORIGIN_VALUE = 'UPDATE_ORIGIN_VALUE'
export const UPDATE_DESTINATION_VALUE = 'UPDATE_DESTINATION_VALUE'
export const SUBMIT_DIRECTION_REQUEST = 'SUBMIT_DIRECTION_REQUEST'
export const DATA_RECIEVED = 'DATA_RECIEVED'